name: Run test

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: makes gradlew executable
        run: chmod +x ./gradlew
      - name: enabling gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Run Unit test
        run: ./gradlew testDebugUnitTest
